name: test

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Linter check
        run: npm run lint
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run migration test
        run: npm run test:migration-run
      - name: Run unitest
        run: npm run test
      - name: Run e2e test
        run: npm run test:e2e
